// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtzFHRjAjBt2jcRZMZeN_aZtm4tfoWzA4',
    appId: '1:473251947552:android:012747a2acef805d968845',
    messagingSenderId: '473251947552',
    projectId: 'com-raintocrops-app',
    databaseURL: 'https://com-raintocrops-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'com-raintocrops-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW8TOpSnOwUL7MwqKkiKfZaB0cYEbr8P8',
    appId: '1:473251947552:ios:023cc133cf6a89ff968845',
    messagingSenderId: '473251947552',
    projectId: 'com-raintocrops-app',
    databaseURL: 'https://com-raintocrops-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'com-raintocrops-app.firebasestorage.app',
    androidClientId: '473251947552-k5mujlovpsthtichh56kc95taqkl0esh.apps.googleusercontent.com',
    iosClientId: '473251947552-lbo9p3jdtqn19rbse2qks5r42an7234f.apps.googleusercontent.com',
    iosBundleId: 'com.raintocrops.app.raintocrops',
  );

}